# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: remote.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'remote.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0cremote.proto\x12\x0bremote.grpc\"6\n\x07Message\x12\x0c\n\x04role\x18\x01 \x01(\t\x12\x0f\n\x07\x63ontent\x18\x02 \x01(\t\x12\x0c\n\x04name\x18\x03 \x01(\t\"]\n\x13\x43onversationMetrics\x12\x19\n\x11\x63ompletion_tokens\x18\x01 \x01(\x05\x12\x15\n\rprompt_tokens\x18\x02 \x01(\x05\x12\x14\n\x0ctotal_tokens\x18\x03 \x01(\x05\"\xc5\x01\n\x13\x43onversationRequest\x12\x10\n\x08\x61gent_id\x18\x01 \x01(\t\x12&\n\x08messages\x18\x02 \x03(\x0b\x32\x14.remote.grpc.Message\x12\x42\n\tvariables\x18\x03 \x03(\x0b\x32/.remote.grpc.ConversationRequest.VariablesEntry\x1a\x30\n\x0eVariablesEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"\xe8\x01\n\x14\x43onversationResponse\x12&\n\x08messages\x18\x01 \x03(\x0b\x32\x14.remote.grpc.Message\x12\x43\n\tvariables\x18\x02 \x03(\x0b\x32\x30.remote.grpc.ConversationResponse.VariablesEntry\x12\x31\n\x07metrics\x18\x03 \x01(\x0b\x32 .remote.grpc.ConversationMetrics\x1a\x30\n\x0eVariablesEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"V\n\x0b\x41skResponse\x12\x0e\n\x06result\x18\x01 \x01(\t\x12\x37\n\x0c\x63onversation\x18\x02 \x01(\x0b\x32!.remote.grpc.ConversationResponse\"#\n\x0f\x44\x65scribeRequest\x12\x10\n\x08\x61gent_id\x18\x01 \x01(\t\"3\n\x10\x44\x65scribeResponse\x12\n\n\x02id\x18\x01 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x02 \x01(\t\"5\n\x14\x41skStreamingResponse\x12\x0c\n\x04mark\x18\x01 \x01(\t\x12\x0f\n\x07\x63ontent\x18\x02 \x01(\t2\xef\x01\n\rRemoteService\x12\x41\n\x03\x41sk\x12 .remote.grpc.ConversationRequest\x1a\x18.remote.grpc.AskResponse\x12R\n\tAskStream\x12 .remote.grpc.ConversationRequest\x1a!.remote.grpc.AskStreamingResponse0\x01\x12G\n\x08\x44\x65scribe\x12\x1c.remote.grpc.DescribeRequest\x1a\x1d.remote.grpc.DescribeResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'remote_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CONVERSATIONREQUEST_VARIABLESENTRY']._loaded_options = None
  _globals['_CONVERSATIONREQUEST_VARIABLESENTRY']._serialized_options = b'8\001'
  _globals['_CONVERSATIONRESPONSE_VARIABLESENTRY']._loaded_options = None
  _globals['_CONVERSATIONRESPONSE_VARIABLESENTRY']._serialized_options = b'8\001'
  _globals['_MESSAGE']._serialized_start=29
  _globals['_MESSAGE']._serialized_end=83
  _globals['_CONVERSATIONMETRICS']._serialized_start=85
  _globals['_CONVERSATIONMETRICS']._serialized_end=178
  _globals['_CONVERSATIONREQUEST']._serialized_start=181
  _globals['_CONVERSATIONREQUEST']._serialized_end=378
  _globals['_CONVERSATIONREQUEST_VARIABLESENTRY']._serialized_start=330
  _globals['_CONVERSATIONREQUEST_VARIABLESENTRY']._serialized_end=378
  _globals['_CONVERSATIONRESPONSE']._serialized_start=381
  _globals['_CONVERSATIONRESPONSE']._serialized_end=613
  _globals['_CONVERSATIONRESPONSE_VARIABLESENTRY']._serialized_start=330
  _globals['_CONVERSATIONRESPONSE_VARIABLESENTRY']._serialized_end=378
  _globals['_ASKRESPONSE']._serialized_start=615
  _globals['_ASKRESPONSE']._serialized_end=701
  _globals['_DESCRIBEREQUEST']._serialized_start=703
  _globals['_DESCRIBEREQUEST']._serialized_end=738
  _globals['_DESCRIBERESPONSE']._serialized_start=740
  _globals['_DESCRIBERESPONSE']._serialized_end=791
  _globals['_ASKSTREAMINGRESPONSE']._serialized_start=793
  _globals['_ASKSTREAMINGRESPONSE']._serialized_end=846
  _globals['_REMOTESERVICE']._serialized_start=849
  _globals['_REMOTESERVICE']._serialized_end=1088
# @@protoc_insertion_point(module_scope)
