# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import remote_pb2 as remote__pb2

GRPC_GENERATED_VERSION = '1.66.2'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in remote_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class RemoteServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Ask = channel.unary_unary(
                '/remote.grpc.RemoteService/Ask',
                request_serializer=remote__pb2.ConversationRequest.SerializeToString,
                response_deserializer=remote__pb2.AskResponse.FromString,
                _registered_method=True)
        self.AskStream = channel.unary_stream(
                '/remote.grpc.RemoteService/AskStream',
                request_serializer=remote__pb2.ConversationRequest.SerializeToString,
                response_deserializer=remote__pb2.AskStreamingResponse.FromString,
                _registered_method=True)
        self.Describe = channel.unary_unary(
                '/remote.grpc.RemoteService/Describe',
                request_serializer=remote__pb2.DescribeRequest.SerializeToString,
                response_deserializer=remote__pb2.DescribeResponse.FromString,
                _registered_method=True)


class RemoteServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Ask(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AskStream(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Describe(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_RemoteServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Ask': grpc.unary_unary_rpc_method_handler(
                    servicer.Ask,
                    request_deserializer=remote__pb2.ConversationRequest.FromString,
                    response_serializer=remote__pb2.AskResponse.SerializeToString,
            ),
            'AskStream': grpc.unary_stream_rpc_method_handler(
                    servicer.AskStream,
                    request_deserializer=remote__pb2.ConversationRequest.FromString,
                    response_serializer=remote__pb2.AskStreamingResponse.SerializeToString,
            ),
            'Describe': grpc.unary_unary_rpc_method_handler(
                    servicer.Describe,
                    request_deserializer=remote__pb2.DescribeRequest.FromString,
                    response_serializer=remote__pb2.DescribeResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'remote.grpc.RemoteService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('remote.grpc.RemoteService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class RemoteService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Ask(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/remote.grpc.RemoteService/Ask',
            remote__pb2.ConversationRequest.SerializeToString,
            remote__pb2.AskResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AskStream(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/remote.grpc.RemoteService/AskStream',
            remote__pb2.ConversationRequest.SerializeToString,
            remote__pb2.AskStreamingResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Describe(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/remote.grpc.RemoteService/Describe',
            remote__pb2.DescribeRequest.SerializeToString,
            remote__pb2.DescribeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
